project:
  type: website
  output-dir: docs
  resources:
    - fonts/*.woff2
    - resume.html
    - publications.html
    - packages.html

filters:
  - iconify

website:
  title: "Dylan Pieper"
  navbar:
    right:
      - href: index.qmd#about
        text: "About"
      - href: index.qmd#software
        text: "Software"
      - href: index.qmd#experience
        text: "Experience"
      - href: index.qmd#talks
        text: "Talks"
      - href: index.qmd#research
        text: "Research"

format:
  html:
    theme:
      - lux
      - custom.scss
    css: styles.css
    toc: true
    favicon: favicon/favicon.ico
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
          <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;600;700&display=swap">
          <link rel="preload" href="/fonts/althera.woff2" as="font" type="font/woff2" crossorigin>
          <link rel="apple-touch-icon" sizes="180x180" href="favicon/apple-touch-icon.png">
          <link rel="icon" type="image/png" sizes="96x96" href="favicon/favicon-96x96.png">
          <link rel="icon" type="image/svg+xml" href="favicon/favicon.svg">
          <link rel="manifest" href="favicon/site.webmanifest">

editor: visual
