project:
  type: website
  output-dir: docs

website:
  title: "Dylan Pieper"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: packages.qmd
        text: Packages
        
format:
  html:
    theme: lux
    toc: true

editor: visual