project:
  type: website
  output-dir: docs

website:
  title: "Dylan Pieper"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog/index.qmd
        text: Blog
      - href: publications.qmd
        text: Publications
      - href: packages.qmd
        text: Packages
      - href: media/Dylan-Pieper-Resume.pdf
        text: Resume
        
format:
  html:
    theme:
      - lux
    css: styles.css
    toc: true

editor: visual