project:
  type: website
  output-dir: docs

filters:
  - iconify

website:
  title: "Dylan Pieper"
  navbar:
    left:
      - href: index.qmd
        text: "{{< iconify bi house >}} Home"
      - href: blog/index.qmd
        text: "{{< iconify bi journal >}} Blog"
      - href: publications.qmd
        text: "{{< iconify bi journal-text >}} Publications"
      - href: packages.qmd
        text: "{{< iconify bi boxes >}} Packages"
      - href: consulting.qmd
        text: "{{< iconify bi briefcase >}} Consulting"
      - href: media/Dylan-Pieper-Resume.pdf
        text: "{{< iconify bi file-person >}} Resume"
        
format:
  html:
    theme:
      - lux
    css: styles.css
    toc: true
    favicon: favicon/favicon.ico
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
          <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
          <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
          <link rel="apple-touch-icon" sizes="180x180" href="favicon/apple-touch-icon.png">
          <link rel="icon" type="image/png" sizes="32x32" href="favicon/favicon-32x32.png">
          <link rel="icon" type="image/png" sizes="16x16" href="favicon/favicon-16x16.png">
          <link rel="manifest" href="favicon/site.webmanifest">

editor: visual